// <auto-generated />
using Clientes.Persistence.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Clientes.Persistence.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201219122946_Inicializar")]
    partial class Inicializar
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Clientes")
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Clientes.Domain.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Celular")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sexo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Pacientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Apellidos = "Apellido 1",
                            Celular = "+51942024657",
                            Dni = "76368636",
                            Email = "paciente1@gmail.com",
                            Nombres = "Nombre 1",
                            Sexo = 1
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Apellidos = "Apellido 2",
                            Celular = "+51942024658",
                            Dni = "76368637",
                            Email = "paciente2@gmail.com",
                            Nombres = "Nombre 2",
                            Sexo = 0
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Apellidos = "Apellido 3",
                            Celular = "+51942024659",
                            Dni = "76368638",
                            Email = "paciente3@gmail.com",
                            Nombres = "Nombre 3",
                            Sexo = 1
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Apellidos = "Apellido 4",
                            Celular = "+51942024660",
                            Dni = "76368639",
                            Email = "paciente4@gmail.com",
                            Nombres = "Nombre 4",
                            Sexo = 0
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Apellidos = "Apellido 5",
                            Celular = "+51942024661",
                            Dni = "76368640",
                            Email = "paciente5@gmail.com",
                            Nombres = "Nombre 5",
                            Sexo = 1
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Apellidos = "Apellido 6",
                            Celular = "+51942024662",
                            Dni = "76368641",
                            Email = "paciente6@gmail.com",
                            Nombres = "Nombre 6",
                            Sexo = 0
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            Apellidos = "Apellido 7",
                            Celular = "+51942024663",
                            Dni = "76368642",
                            Email = "paciente7@gmail.com",
                            Nombres = "Nombre 7",
                            Sexo = 1
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            Apellidos = "Apellido 8",
                            Celular = "+51942024664",
                            Dni = "76368643",
                            Email = "paciente8@gmail.com",
                            Nombres = "Nombre 8",
                            Sexo = 0
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            Apellidos = "Apellido 9",
                            Celular = "+51942024665",
                            Dni = "76368644",
                            Email = "paciente9@gmail.com",
                            Nombres = "Nombre 9",
                            Sexo = 1
                        },
                        new
                        {
                            Id = 10,
                            Activo = true,
                            Apellidos = "Apellido 10",
                            Celular = "+51942024666",
                            Dni = "76368645",
                            Email = "paciente10@gmail.com",
                            Nombres = "Nombre 10",
                            Sexo = 0
                        },
                        new
                        {
                            Id = 11,
                            Activo = true,
                            Apellidos = "Apellido 11",
                            Celular = "+51942024667",
                            Dni = "76368646",
                            Email = "paciente11@gmail.com",
                            Nombres = "Nombre 11",
                            Sexo = 1
                        },
                        new
                        {
                            Id = 12,
                            Activo = true,
                            Apellidos = "Apellido 12",
                            Celular = "+51942024668",
                            Dni = "76368647",
                            Email = "paciente12@gmail.com",
                            Nombres = "Nombre 12",
                            Sexo = 0
                        },
                        new
                        {
                            Id = 13,
                            Activo = true,
                            Apellidos = "Apellido 13",
                            Celular = "+51942024669",
                            Dni = "76368648",
                            Email = "paciente13@gmail.com",
                            Nombres = "Nombre 13",
                            Sexo = 1
                        },
                        new
                        {
                            Id = 14,
                            Activo = true,
                            Apellidos = "Apellido 14",
                            Celular = "+51942024670",
                            Dni = "76368649",
                            Email = "paciente14@gmail.com",
                            Nombres = "Nombre 14",
                            Sexo = 0
                        },
                        new
                        {
                            Id = 15,
                            Activo = true,
                            Apellidos = "Apellido 15",
                            Celular = "+51942024671",
                            Dni = "76368650",
                            Email = "paciente15@gmail.com",
                            Nombres = "Nombre 15",
                            Sexo = 1
                        },
                        new
                        {
                            Id = 16,
                            Activo = true,
                            Apellidos = "Apellido 16",
                            Celular = "+51942024672",
                            Dni = "76368651",
                            Email = "paciente16@gmail.com",
                            Nombres = "Nombre 16",
                            Sexo = 0
                        },
                        new
                        {
                            Id = 17,
                            Activo = true,
                            Apellidos = "Apellido 17",
                            Celular = "+51942024673",
                            Dni = "76368652",
                            Email = "paciente17@gmail.com",
                            Nombres = "Nombre 17",
                            Sexo = 1
                        },
                        new
                        {
                            Id = 18,
                            Activo = true,
                            Apellidos = "Apellido 18",
                            Celular = "+51942024674",
                            Dni = "76368653",
                            Email = "paciente18@gmail.com",
                            Nombres = "Nombre 18",
                            Sexo = 0
                        },
                        new
                        {
                            Id = 19,
                            Activo = true,
                            Apellidos = "Apellido 19",
                            Celular = "+51942024675",
                            Dni = "76368654",
                            Email = "paciente19@gmail.com",
                            Nombres = "Nombre 19",
                            Sexo = 1
                        },
                        new
                        {
                            Id = 20,
                            Activo = true,
                            Apellidos = "Apellido 20",
                            Celular = "+51942024676",
                            Dni = "76368655",
                            Email = "paciente20@gmail.com",
                            Nombres = "Nombre 20",
                            Sexo = 0
                        },
                        new
                        {
                            Id = 21,
                            Activo = true,
                            Apellidos = "Apellido 21",
                            Celular = "+51942024677",
                            Dni = "76368656",
                            Email = "paciente21@gmail.com",
                            Nombres = "Nombre 21",
                            Sexo = 1
                        },
                        new
                        {
                            Id = 22,
                            Activo = true,
                            Apellidos = "Apellido 22",
                            Celular = "+51942024678",
                            Dni = "76368657",
                            Email = "paciente22@gmail.com",
                            Nombres = "Nombre 22",
                            Sexo = 0
                        },
                        new
                        {
                            Id = 23,
                            Activo = true,
                            Apellidos = "Apellido 23",
                            Celular = "+51942024679",
                            Dni = "76368658",
                            Email = "paciente23@gmail.com",
                            Nombres = "Nombre 23",
                            Sexo = 1
                        },
                        new
                        {
                            Id = 24,
                            Activo = true,
                            Apellidos = "Apellido 24",
                            Celular = "+51942024680",
                            Dni = "76368659",
                            Email = "paciente24@gmail.com",
                            Nombres = "Nombre 24",
                            Sexo = 0
                        },
                        new
                        {
                            Id = 25,
                            Activo = true,
                            Apellidos = "Apellido 25",
                            Celular = "+51942024681",
                            Dni = "76368660",
                            Email = "paciente25@gmail.com",
                            Nombres = "Nombre 25",
                            Sexo = 1
                        },
                        new
                        {
                            Id = 26,
                            Activo = true,
                            Apellidos = "Apellido 26",
                            Celular = "+51942024682",
                            Dni = "76368661",
                            Email = "paciente26@gmail.com",
                            Nombres = "Nombre 26",
                            Sexo = 0
                        },
                        new
                        {
                            Id = 27,
                            Activo = true,
                            Apellidos = "Apellido 27",
                            Celular = "+51942024683",
                            Dni = "76368662",
                            Email = "paciente27@gmail.com",
                            Nombres = "Nombre 27",
                            Sexo = 1
                        },
                        new
                        {
                            Id = 28,
                            Activo = true,
                            Apellidos = "Apellido 28",
                            Celular = "+51942024684",
                            Dni = "76368663",
                            Email = "paciente28@gmail.com",
                            Nombres = "Nombre 28",
                            Sexo = 0
                        },
                        new
                        {
                            Id = 29,
                            Activo = true,
                            Apellidos = "Apellido 29",
                            Celular = "+51942024685",
                            Dni = "76368664",
                            Email = "paciente29@gmail.com",
                            Nombres = "Nombre 29",
                            Sexo = 1
                        },
                        new
                        {
                            Id = 30,
                            Activo = true,
                            Apellidos = "Apellido 30",
                            Celular = "+51942024686",
                            Dni = "76368665",
                            Email = "paciente30@gmail.com",
                            Nombres = "Nombre 30",
                            Sexo = 0
                        },
                        new
                        {
                            Id = 31,
                            Activo = true,
                            Apellidos = "Apellido 31",
                            Celular = "+51942024687",
                            Dni = "76368666",
                            Email = "paciente31@gmail.com",
                            Nombres = "Nombre 31",
                            Sexo = 1
                        },
                        new
                        {
                            Id = 32,
                            Activo = true,
                            Apellidos = "Apellido 32",
                            Celular = "+51942024688",
                            Dni = "76368667",
                            Email = "paciente32@gmail.com",
                            Nombres = "Nombre 32",
                            Sexo = 0
                        },
                        new
                        {
                            Id = 33,
                            Activo = true,
                            Apellidos = "Apellido 33",
                            Celular = "+51942024689",
                            Dni = "76368668",
                            Email = "paciente33@gmail.com",
                            Nombres = "Nombre 33",
                            Sexo = 1
                        },
                        new
                        {
                            Id = 34,
                            Activo = true,
                            Apellidos = "Apellido 34",
                            Celular = "+51942024690",
                            Dni = "76368669",
                            Email = "paciente34@gmail.com",
                            Nombres = "Nombre 34",
                            Sexo = 0
                        },
                        new
                        {
                            Id = 35,
                            Activo = true,
                            Apellidos = "Apellido 35",
                            Celular = "+51942024691",
                            Dni = "76368670",
                            Email = "paciente35@gmail.com",
                            Nombres = "Nombre 35",
                            Sexo = 1
                        },
                        new
                        {
                            Id = 36,
                            Activo = true,
                            Apellidos = "Apellido 36",
                            Celular = "+51942024692",
                            Dni = "76368671",
                            Email = "paciente36@gmail.com",
                            Nombres = "Nombre 36",
                            Sexo = 0
                        },
                        new
                        {
                            Id = 37,
                            Activo = true,
                            Apellidos = "Apellido 37",
                            Celular = "+51942024693",
                            Dni = "76368672",
                            Email = "paciente37@gmail.com",
                            Nombres = "Nombre 37",
                            Sexo = 1
                        },
                        new
                        {
                            Id = 38,
                            Activo = true,
                            Apellidos = "Apellido 38",
                            Celular = "+51942024694",
                            Dni = "76368673",
                            Email = "paciente38@gmail.com",
                            Nombres = "Nombre 38",
                            Sexo = 0
                        },
                        new
                        {
                            Id = 39,
                            Activo = true,
                            Apellidos = "Apellido 39",
                            Celular = "+51942024695",
                            Dni = "76368674",
                            Email = "paciente39@gmail.com",
                            Nombres = "Nombre 39",
                            Sexo = 1
                        },
                        new
                        {
                            Id = 40,
                            Activo = true,
                            Apellidos = "Apellido 40",
                            Celular = "+51942024696",
                            Dni = "76368675",
                            Email = "paciente40@gmail.com",
                            Nombres = "Nombre 40",
                            Sexo = 0
                        },
                        new
                        {
                            Id = 41,
                            Activo = true,
                            Apellidos = "Apellido 41",
                            Celular = "+51942024697",
                            Dni = "76368676",
                            Email = "paciente41@gmail.com",
                            Nombres = "Nombre 41",
                            Sexo = 1
                        },
                        new
                        {
                            Id = 42,
                            Activo = true,
                            Apellidos = "Apellido 42",
                            Celular = "+51942024698",
                            Dni = "76368677",
                            Email = "paciente42@gmail.com",
                            Nombres = "Nombre 42",
                            Sexo = 0
                        },
                        new
                        {
                            Id = 43,
                            Activo = true,
                            Apellidos = "Apellido 43",
                            Celular = "+51942024699",
                            Dni = "76368678",
                            Email = "paciente43@gmail.com",
                            Nombres = "Nombre 43",
                            Sexo = 1
                        },
                        new
                        {
                            Id = 44,
                            Activo = true,
                            Apellidos = "Apellido 44",
                            Celular = "+51942024700",
                            Dni = "76368679",
                            Email = "paciente44@gmail.com",
                            Nombres = "Nombre 44",
                            Sexo = 0
                        },
                        new
                        {
                            Id = 45,
                            Activo = true,
                            Apellidos = "Apellido 45",
                            Celular = "+51942024701",
                            Dni = "76368680",
                            Email = "paciente45@gmail.com",
                            Nombres = "Nombre 45",
                            Sexo = 1
                        },
                        new
                        {
                            Id = 46,
                            Activo = true,
                            Apellidos = "Apellido 46",
                            Celular = "+51942024702",
                            Dni = "76368681",
                            Email = "paciente46@gmail.com",
                            Nombres = "Nombre 46",
                            Sexo = 0
                        },
                        new
                        {
                            Id = 47,
                            Activo = true,
                            Apellidos = "Apellido 47",
                            Celular = "+51942024703",
                            Dni = "76368682",
                            Email = "paciente47@gmail.com",
                            Nombres = "Nombre 47",
                            Sexo = 1
                        },
                        new
                        {
                            Id = 48,
                            Activo = true,
                            Apellidos = "Apellido 48",
                            Celular = "+51942024704",
                            Dni = "76368683",
                            Email = "paciente48@gmail.com",
                            Nombres = "Nombre 48",
                            Sexo = 0
                        },
                        new
                        {
                            Id = 49,
                            Activo = true,
                            Apellidos = "Apellido 49",
                            Celular = "+51942024705",
                            Dni = "76368684",
                            Email = "paciente49@gmail.com",
                            Nombres = "Nombre 49",
                            Sexo = 1
                        },
                        new
                        {
                            Id = 50,
                            Activo = true,
                            Apellidos = "Apellido 50",
                            Celular = "+51942024706",
                            Dni = "76368685",
                            Email = "paciente50@gmail.com",
                            Nombres = "Nombre 50",
                            Sexo = 0
                        },
                        new
                        {
                            Id = 51,
                            Activo = true,
                            Apellidos = "Apellido 51",
                            Celular = "+51942024707",
                            Dni = "76368686",
                            Email = "paciente51@gmail.com",
                            Nombres = "Nombre 51",
                            Sexo = 1
                        },
                        new
                        {
                            Id = 52,
                            Activo = true,
                            Apellidos = "Apellido 52",
                            Celular = "+51942024708",
                            Dni = "76368687",
                            Email = "paciente52@gmail.com",
                            Nombres = "Nombre 52",
                            Sexo = 0
                        },
                        new
                        {
                            Id = 53,
                            Activo = true,
                            Apellidos = "Apellido 53",
                            Celular = "+51942024709",
                            Dni = "76368688",
                            Email = "paciente53@gmail.com",
                            Nombres = "Nombre 53",
                            Sexo = 1
                        },
                        new
                        {
                            Id = 54,
                            Activo = true,
                            Apellidos = "Apellido 54",
                            Celular = "+51942024710",
                            Dni = "76368689",
                            Email = "paciente54@gmail.com",
                            Nombres = "Nombre 54",
                            Sexo = 0
                        },
                        new
                        {
                            Id = 55,
                            Activo = true,
                            Apellidos = "Apellido 55",
                            Celular = "+51942024711",
                            Dni = "76368690",
                            Email = "paciente55@gmail.com",
                            Nombres = "Nombre 55",
                            Sexo = 1
                        },
                        new
                        {
                            Id = 56,
                            Activo = true,
                            Apellidos = "Apellido 56",
                            Celular = "+51942024712",
                            Dni = "76368691",
                            Email = "paciente56@gmail.com",
                            Nombres = "Nombre 56",
                            Sexo = 0
                        },
                        new
                        {
                            Id = 57,
                            Activo = true,
                            Apellidos = "Apellido 57",
                            Celular = "+51942024713",
                            Dni = "76368692",
                            Email = "paciente57@gmail.com",
                            Nombres = "Nombre 57",
                            Sexo = 1
                        },
                        new
                        {
                            Id = 58,
                            Activo = true,
                            Apellidos = "Apellido 58",
                            Celular = "+51942024714",
                            Dni = "76368693",
                            Email = "paciente58@gmail.com",
                            Nombres = "Nombre 58",
                            Sexo = 0
                        },
                        new
                        {
                            Id = 59,
                            Activo = true,
                            Apellidos = "Apellido 59",
                            Celular = "+51942024715",
                            Dni = "76368694",
                            Email = "paciente59@gmail.com",
                            Nombres = "Nombre 59",
                            Sexo = 1
                        },
                        new
                        {
                            Id = 60,
                            Activo = true,
                            Apellidos = "Apellido 60",
                            Celular = "+51942024716",
                            Dni = "76368695",
                            Email = "paciente60@gmail.com",
                            Nombres = "Nombre 60",
                            Sexo = 0
                        },
                        new
                        {
                            Id = 61,
                            Activo = true,
                            Apellidos = "Apellido 61",
                            Celular = "+51942024717",
                            Dni = "76368696",
                            Email = "paciente61@gmail.com",
                            Nombres = "Nombre 61",
                            Sexo = 1
                        },
                        new
                        {
                            Id = 62,
                            Activo = true,
                            Apellidos = "Apellido 62",
                            Celular = "+51942024718",
                            Dni = "76368697",
                            Email = "paciente62@gmail.com",
                            Nombres = "Nombre 62",
                            Sexo = 0
                        },
                        new
                        {
                            Id = 63,
                            Activo = true,
                            Apellidos = "Apellido 63",
                            Celular = "+51942024719",
                            Dni = "76368698",
                            Email = "paciente63@gmail.com",
                            Nombres = "Nombre 63",
                            Sexo = 1
                        },
                        new
                        {
                            Id = 64,
                            Activo = true,
                            Apellidos = "Apellido 64",
                            Celular = "+51942024720",
                            Dni = "76368699",
                            Email = "paciente64@gmail.com",
                            Nombres = "Nombre 64",
                            Sexo = 0
                        },
                        new
                        {
                            Id = 65,
                            Activo = true,
                            Apellidos = "Apellido 65",
                            Celular = "+51942024721",
                            Dni = "76368700",
                            Email = "paciente65@gmail.com",
                            Nombres = "Nombre 65",
                            Sexo = 1
                        },
                        new
                        {
                            Id = 66,
                            Activo = true,
                            Apellidos = "Apellido 66",
                            Celular = "+51942024722",
                            Dni = "76368701",
                            Email = "paciente66@gmail.com",
                            Nombres = "Nombre 66",
                            Sexo = 0
                        },
                        new
                        {
                            Id = 67,
                            Activo = true,
                            Apellidos = "Apellido 67",
                            Celular = "+51942024723",
                            Dni = "76368702",
                            Email = "paciente67@gmail.com",
                            Nombres = "Nombre 67",
                            Sexo = 1
                        },
                        new
                        {
                            Id = 68,
                            Activo = true,
                            Apellidos = "Apellido 68",
                            Celular = "+51942024724",
                            Dni = "76368703",
                            Email = "paciente68@gmail.com",
                            Nombres = "Nombre 68",
                            Sexo = 0
                        },
                        new
                        {
                            Id = 69,
                            Activo = true,
                            Apellidos = "Apellido 69",
                            Celular = "+51942024725",
                            Dni = "76368704",
                            Email = "paciente69@gmail.com",
                            Nombres = "Nombre 69",
                            Sexo = 1
                        },
                        new
                        {
                            Id = 70,
                            Activo = true,
                            Apellidos = "Apellido 70",
                            Celular = "+51942024726",
                            Dni = "76368705",
                            Email = "paciente70@gmail.com",
                            Nombres = "Nombre 70",
                            Sexo = 0
                        },
                        new
                        {
                            Id = 71,
                            Activo = true,
                            Apellidos = "Apellido 71",
                            Celular = "+51942024727",
                            Dni = "76368706",
                            Email = "paciente71@gmail.com",
                            Nombres = "Nombre 71",
                            Sexo = 1
                        },
                        new
                        {
                            Id = 72,
                            Activo = true,
                            Apellidos = "Apellido 72",
                            Celular = "+51942024728",
                            Dni = "76368707",
                            Email = "paciente72@gmail.com",
                            Nombres = "Nombre 72",
                            Sexo = 0
                        },
                        new
                        {
                            Id = 73,
                            Activo = true,
                            Apellidos = "Apellido 73",
                            Celular = "+51942024729",
                            Dni = "76368708",
                            Email = "paciente73@gmail.com",
                            Nombres = "Nombre 73",
                            Sexo = 1
                        },
                        new
                        {
                            Id = 74,
                            Activo = true,
                            Apellidos = "Apellido 74",
                            Celular = "+51942024730",
                            Dni = "76368709",
                            Email = "paciente74@gmail.com",
                            Nombres = "Nombre 74",
                            Sexo = 0
                        },
                        new
                        {
                            Id = 75,
                            Activo = true,
                            Apellidos = "Apellido 75",
                            Celular = "+51942024731",
                            Dni = "76368710",
                            Email = "paciente75@gmail.com",
                            Nombres = "Nombre 75",
                            Sexo = 1
                        },
                        new
                        {
                            Id = 76,
                            Activo = true,
                            Apellidos = "Apellido 76",
                            Celular = "+51942024732",
                            Dni = "76368711",
                            Email = "paciente76@gmail.com",
                            Nombres = "Nombre 76",
                            Sexo = 0
                        },
                        new
                        {
                            Id = 77,
                            Activo = true,
                            Apellidos = "Apellido 77",
                            Celular = "+51942024733",
                            Dni = "76368712",
                            Email = "paciente77@gmail.com",
                            Nombres = "Nombre 77",
                            Sexo = 1
                        },
                        new
                        {
                            Id = 78,
                            Activo = true,
                            Apellidos = "Apellido 78",
                            Celular = "+51942024734",
                            Dni = "76368713",
                            Email = "paciente78@gmail.com",
                            Nombres = "Nombre 78",
                            Sexo = 0
                        },
                        new
                        {
                            Id = 79,
                            Activo = true,
                            Apellidos = "Apellido 79",
                            Celular = "+51942024735",
                            Dni = "76368714",
                            Email = "paciente79@gmail.com",
                            Nombres = "Nombre 79",
                            Sexo = 1
                        },
                        new
                        {
                            Id = 80,
                            Activo = true,
                            Apellidos = "Apellido 80",
                            Celular = "+51942024736",
                            Dni = "76368715",
                            Email = "paciente80@gmail.com",
                            Nombres = "Nombre 80",
                            Sexo = 0
                        },
                        new
                        {
                            Id = 81,
                            Activo = true,
                            Apellidos = "Apellido 81",
                            Celular = "+51942024737",
                            Dni = "76368716",
                            Email = "paciente81@gmail.com",
                            Nombres = "Nombre 81",
                            Sexo = 1
                        },
                        new
                        {
                            Id = 82,
                            Activo = true,
                            Apellidos = "Apellido 82",
                            Celular = "+51942024738",
                            Dni = "76368717",
                            Email = "paciente82@gmail.com",
                            Nombres = "Nombre 82",
                            Sexo = 0
                        },
                        new
                        {
                            Id = 83,
                            Activo = true,
                            Apellidos = "Apellido 83",
                            Celular = "+51942024739",
                            Dni = "76368718",
                            Email = "paciente83@gmail.com",
                            Nombres = "Nombre 83",
                            Sexo = 1
                        },
                        new
                        {
                            Id = 84,
                            Activo = true,
                            Apellidos = "Apellido 84",
                            Celular = "+51942024740",
                            Dni = "76368719",
                            Email = "paciente84@gmail.com",
                            Nombres = "Nombre 84",
                            Sexo = 0
                        },
                        new
                        {
                            Id = 85,
                            Activo = true,
                            Apellidos = "Apellido 85",
                            Celular = "+51942024741",
                            Dni = "76368720",
                            Email = "paciente85@gmail.com",
                            Nombres = "Nombre 85",
                            Sexo = 1
                        },
                        new
                        {
                            Id = 86,
                            Activo = true,
                            Apellidos = "Apellido 86",
                            Celular = "+51942024742",
                            Dni = "76368721",
                            Email = "paciente86@gmail.com",
                            Nombres = "Nombre 86",
                            Sexo = 0
                        },
                        new
                        {
                            Id = 87,
                            Activo = true,
                            Apellidos = "Apellido 87",
                            Celular = "+51942024743",
                            Dni = "76368722",
                            Email = "paciente87@gmail.com",
                            Nombres = "Nombre 87",
                            Sexo = 1
                        },
                        new
                        {
                            Id = 88,
                            Activo = true,
                            Apellidos = "Apellido 88",
                            Celular = "+51942024744",
                            Dni = "76368723",
                            Email = "paciente88@gmail.com",
                            Nombres = "Nombre 88",
                            Sexo = 0
                        },
                        new
                        {
                            Id = 89,
                            Activo = true,
                            Apellidos = "Apellido 89",
                            Celular = "+51942024745",
                            Dni = "76368724",
                            Email = "paciente89@gmail.com",
                            Nombres = "Nombre 89",
                            Sexo = 1
                        },
                        new
                        {
                            Id = 90,
                            Activo = true,
                            Apellidos = "Apellido 90",
                            Celular = "+51942024746",
                            Dni = "76368725",
                            Email = "paciente90@gmail.com",
                            Nombres = "Nombre 90",
                            Sexo = 0
                        },
                        new
                        {
                            Id = 91,
                            Activo = true,
                            Apellidos = "Apellido 91",
                            Celular = "+51942024747",
                            Dni = "76368726",
                            Email = "paciente91@gmail.com",
                            Nombres = "Nombre 91",
                            Sexo = 1
                        },
                        new
                        {
                            Id = 92,
                            Activo = true,
                            Apellidos = "Apellido 92",
                            Celular = "+51942024748",
                            Dni = "76368727",
                            Email = "paciente92@gmail.com",
                            Nombres = "Nombre 92",
                            Sexo = 0
                        },
                        new
                        {
                            Id = 93,
                            Activo = true,
                            Apellidos = "Apellido 93",
                            Celular = "+51942024749",
                            Dni = "76368728",
                            Email = "paciente93@gmail.com",
                            Nombres = "Nombre 93",
                            Sexo = 1
                        },
                        new
                        {
                            Id = 94,
                            Activo = true,
                            Apellidos = "Apellido 94",
                            Celular = "+51942024750",
                            Dni = "76368729",
                            Email = "paciente94@gmail.com",
                            Nombres = "Nombre 94",
                            Sexo = 0
                        },
                        new
                        {
                            Id = 95,
                            Activo = true,
                            Apellidos = "Apellido 95",
                            Celular = "+51942024751",
                            Dni = "76368730",
                            Email = "paciente95@gmail.com",
                            Nombres = "Nombre 95",
                            Sexo = 1
                        },
                        new
                        {
                            Id = 96,
                            Activo = true,
                            Apellidos = "Apellido 96",
                            Celular = "+51942024752",
                            Dni = "76368731",
                            Email = "paciente96@gmail.com",
                            Nombres = "Nombre 96",
                            Sexo = 0
                        },
                        new
                        {
                            Id = 97,
                            Activo = true,
                            Apellidos = "Apellido 97",
                            Celular = "+51942024753",
                            Dni = "76368732",
                            Email = "paciente97@gmail.com",
                            Nombres = "Nombre 97",
                            Sexo = 1
                        },
                        new
                        {
                            Id = 98,
                            Activo = true,
                            Apellidos = "Apellido 98",
                            Celular = "+51942024754",
                            Dni = "76368733",
                            Email = "paciente98@gmail.com",
                            Nombres = "Nombre 98",
                            Sexo = 0
                        },
                        new
                        {
                            Id = 99,
                            Activo = true,
                            Apellidos = "Apellido 99",
                            Celular = "+51942024755",
                            Dni = "76368734",
                            Email = "paciente99@gmail.com",
                            Nombres = "Nombre 99",
                            Sexo = 1
                        },
                        new
                        {
                            Id = 100,
                            Activo = true,
                            Apellidos = "Apellido 100",
                            Celular = "+51942024756",
                            Dni = "76368735",
                            Email = "paciente100@gmail.com",
                            Nombres = "Nombre 100",
                            Sexo = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
