// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Personal.Persistence.Database;

namespace Personal.Persistence.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201219010518_Inicializar")]
    partial class Inicializar
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Personal")
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Personal.Domain.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Empleados");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Apellidos = "Apellido 1",
                            Dni = "76368626",
                            Nombres = "Nombre 1"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Apellidos = "Apellido 2",
                            Dni = "76368627",
                            Nombres = "Nombre 2"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Apellidos = "Apellido 3",
                            Dni = "76368628",
                            Nombres = "Nombre 3"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Apellidos = "Apellido 4",
                            Dni = "76368629",
                            Nombres = "Nombre 4"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Apellidos = "Apellido 5",
                            Dni = "76368630",
                            Nombres = "Nombre 5"
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Apellidos = "Apellido 6",
                            Dni = "76368631",
                            Nombres = "Nombre 6"
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            Apellidos = "Apellido 7",
                            Dni = "76368632",
                            Nombres = "Nombre 7"
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            Apellidos = "Apellido 8",
                            Dni = "76368633",
                            Nombres = "Nombre 8"
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            Apellidos = "Apellido 9",
                            Dni = "76368634",
                            Nombres = "Nombre 9"
                        },
                        new
                        {
                            Id = 10,
                            Activo = true,
                            Apellidos = "Apellido 10",
                            Dni = "76368635",
                            Nombres = "Nombre 10"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
